openapi: 3.0.1
info:
  title: Clients
  version: 1.0.0
paths:
  /api/affiliatets/autologin:
    get:
      summary: Get link for auto-login
      description:
        Returns link that allows to auto-login into trader personal area.
        Link works only for newly registered leads, i.e. leads without deposit.
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
          description: CRM Lead ID
      responses:
        '200':
          description: Correct response
          content:
            application/json:
              schema:
                properties:
                  loginUrl:
                    type: string
                    description: Link for automatic login (i.e. without login/pass)
                example:
                  loginUrl: https://dev02.bo.avrath.net/Account/TokenLogin?code=3fda080ae93840f68aa4055e3fc7b8ac434da51d64e0458390394766c1855235
        '404':
          description: CRM Lead ID not found
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                example:
                  message: client not found
  /api/affiliatets/clientinfo:
    get:
      summary: Get client info
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
          description: CRM Lead ID
      responses:
        '200':
          description: Correct response
          content:
            application/json:
              schema:
                type: object
                properties: 
                  action:
                    type: string
                    description: type of profile #(always Lead)
                  status:
                    type: string
                    description: if the registration considered as an active (real account) or demo
                  rdate:
                    type: string
                    description: date of registration
                  lastLoginDate:
                    type: string
                    description: date of Lead's last login
                  leadStatus:
                    type: string
                    description: Lead status
                  country: 
                    type: string
                    description: Lead's country (ISO code 2 characters)
                  promoCode:
                    type: string
                    description: Lead's promo
                  crmLeadId:
                    type: string
                    description: ID of Lead in CRM system
                  leadSource:
                    type: string
                    description: method Lead was created with (integration/manual/import/backoffice)
                  leadSourceType:
                    type: string
                    description: name of Lead Source
                  mtmGroupName: 
                    type: string
                    description: Partner's goup name in MetaTrader4
                  partnerName:
                    type: string
                    description: Partner's name in CRM system
                  email:
                    type: string
                    description: Lead's email
                  firstName:
                    type: string
                    description: Lead's first name
                  lastName: 
                    type: string
                    description: Lead's surname
                  countyCode:
                    type: string
                    description: Lead's country (ISO code 2 characters)
                  balance:
                    type: string
                    description: Lead's current balance
                  tradingAccounts:
                    description: list of Lead's tranding accounts
                    type: array
                    items:
                      properties:
                        login:
                          type: string
                          description: ID of trading account in trading platform
                        currency: 
                          type: string
                          description: currency of account
                  ftdDate:
                    type: string
                    description: date of the first trading deposit
                  transactions:
                    type: array
                    items: 
                      $ref: '#/components/schemas/trans'
                example:
                  action: "lead"
                  status: "lead"
                  rdate: "2017-12-28 00:00:01"
                  lastLoginDate: "2018-01-01 00:00:00"
                  leadStatus: "new"
                  country: Russia
                  promoCode: "111"
                  crmLeadId: "111111"
                  leadSource: integration
                  leadSourceType: "Source1"
                  mtmGroupName: "xxx-xxx-xxx"
                  partnerName: "Partner1"
                  email: "example@example.com"
                  firstName: "John"
                  lastName: "Smith"
                  countryCode: "RU"
                  currency: "USD"
                  balance: "1000"
                  tradingAccounts:
                  - login: "1111111111"
                    currency: USD
                  ftdDate: "2018-01-31 13:30:52"
                  transactions:
                  - rdate: "2018-01-31 13:30:52"
                    traderID: "1111111111"
                    tranzID: "1111111"
                    type: "deposits"
                    amount: "1000"
                    currency: "USD"
                    status: "approval"
                    crmLeadId: "111111"
        '404':
          description: CRM Lead ID not found
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                example:
                  message: client not found
  /api/affiliatets/transactions:
    get:
      summary: Deposits and withdrawals. Data of all Partners.
      description: Returns information on deposits and withdrawals transactions.
      parameters:
        - $ref: '#/components/parameters/fromParam'
        - $ref: '#/components/parameters/toParam'
        - $ref: '#/components/parameters/rowsParam'
        - $ref: '#/components/parameters/pageParam'
      responses:
        '200':
          description: Correct response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/trans'
  /api/v2/affiliate/transactions:
    get:
      summary: Deposits and withdrawals. Data of specific Partner or promo-code (defined by token).
      description: Returns information on deposits and withdrawals transactions.
      parameters:
        - $ref: '#/components/parameters/fromParam'
        - $ref: '#/components/parameters/toParam'
        - $ref: '#/components/parameters/rowsParam'
        - $ref: '#/components/parameters/pageParam'
      responses:
        '200':
          description: Correct response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/trans'
  /api/affiliatets/stats:
    get:
      summary: Trading transactions. Data of all Partners.
      description: Returns information on trading transactions.
      parameters:
        - $ref: '#/components/parameters/fromParam'
        - $ref: '#/components/parameters/toParam'
        - $ref: '#/components/parameters/rowsParam'
        - $ref: '#/components/parameters/pageParam'
      responses:
        '200':
          description: Correct response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/stats'
  /api/v2/affiliate/stats:
    get:
      summary: Trading transactions. Data of specific Partner or promo-code (defined by token).
      description: Returns information on trading transactions.
      parameters:
        - $ref: '#/components/parameters/fromParam'
        - $ref: '#/components/parameters/toParam'
        - $ref: '#/components/parameters/rowsParam'
        - $ref: '#/components/parameters/pageParam'
      responses:
        '200':
          description: Correct response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/stats'
  /api/affiliatets/registration:
    get:
      summary: Leads registration. Data of all Partners.
      description: Returns information on Leads' registration.
      parameters:
        - $ref: '#/components/parameters/fromParam'
        - $ref: '#/components/parameters/toParam'
        - $ref: '#/components/parameters/rowsParam'
        - $ref: '#/components/parameters/pageParam'
      responses:
        '200':
          description: Correct response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/regs'
  /api/v2/affiliate/registrations:
    get:
      summary: Leads registration. Data of specific Partner or promo-code (defined by token).
      description: Returns information on Leads' registration.
      parameters:
        - $ref: '#/components/parameters/fromParam'
        - $ref: '#/components/parameters/toParam'
        - $ref: '#/components/parameters/rowsParam'
        - $ref: '#/components/parameters/pageParam'
      responses:
        '200':
          description: Correct response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/regs'
components:
  parameters:
    fromParam:
      in: query
      name: from
      description: start of a period
      required: true
      schema:
        type: string
        format: dateTime
      example: "2017-01-01"
    toParam:
      in: query
      name: to
      description: end of a period
      required: true
      schema:
        type: string
        format: dateTime
      example: "2017-01-01"
    rowsParam:
      in: query
      name: rows
      description: number of rows in a page
      required: true
      schema:
        type: integer
      example: 100
    pageParam:
      in: query
      name: page
      description: page number
      required: true
      schema:
        type: integer
      example: 1
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: "To receive the token, go to: <b>SETTINGS</b> > <b>Api token</b> and press <b>GENERATE TOKEN</b>."
  schemas:
    regs:
      type: object
      properties:
        action:
          type: string
          description: type of profile #(always Lead)
        status:
          type: string
          description: if the registration considered as an active (real account) or demo
        rdate:
          type: string
          description: date of registration
        traderID:
          type: string
          description: ID of trading account in trading platform
        lastLoginDate:
          type: string
          description: date of Lead's last login
        leadStatus:
          type: string
          description: Lead status
        country: 
          type: string
          description: Lead's country (ISO code 2 characters)
        promoCode:
          type: string
          description: Lead's promo
        crmLeadId:
          type: string
          description: ID of Lead in CRM system
        leadSource:
          type: string
          description: method Lead was created with (integration/manual/import/backoffice)
        leadSourceType:
          type: string
          description: name of Lead Source
        mtmGroupName: 
          type: string
          description: Partner's goup name in MetaTrader4
        partnerName:
          type: string
          description: Partner's name in CRM system
        email:
          type: string
          description: Lead's email
      example:
        action: lead
        status: lead
        rdate: "2017-01-01 01:01:01"
        traderID: "1111111111"
        lastLoginDate: "2017-01-01 01:11:01"
        leadStatus: hot
        country: RU
        promoCode: "111"
        crmLeadId: "11111"
        leadSource: integration
        leadSourceType: LeadSource1
        mtmGroupName: xxx-xxx-xxx
        partnerName: Partner1
        email: example@example.com
    stats:
      type: object
      properties:
        rdate:
          type: string
          description: date of transaction
        traderID:
          type: string
          description: ID of trading account in trading platform
        tranzID:
          type: string
          description: ID of transaction in trading platform
        type:
          type: string
          description: type of transaction (deposit/withdrawal)
        amount:
          type: string
          description: amount of transaction
        currency:
          type: string
          description: currency of transaction
        status:
          type: string
          description: status of transaction
        usdAmount: 
          type: string
          description: amount of transaction in USD currency
        crmLeadId:
          type: string
          description: ID of a Lead in CRM system
      example:
        rdate: "2017-01-01 01:01:01"
        traderID: "11111111111"
        tranzID: "1"
        type: pnl
        amount: "1000"
        currency: USD
        status: approval
        usdAmount: "1000"
        crmLeadId: "111111"
    trans: 
      type: object
      properties:
        rdate:
          type: string
          description: date of transaction
        traderID:
          type: string
          description: ID of trading account in trading platform
        tranzID:
          type: string
          description: ID of transaction in trading platform
        type:
          type: string
          description: type of transaction (deposit/withdrawal)
        amount:
          type: string
          description: amount of transaction
        currency:
          type: string
          description: currency of transaction
        status:
          type: string
          description: status of transaction
        crmLeadId:
          type: string
          description: ID of a Lead in CRM system
      example:
        rdate: "2017-01-01 01:01:01"
        traderID: "1111111111"
        tranzID: "1"
        type: deposit
        amount: "1000"
        currency: USD
        status: approval
        crmLeadId: "111111"
security:
  - ApiKeyAuth: []
