openapi: 3.0.1
info:
  title: Clients
  version: 1.0.0
servers:
  - url: 'https://secure.forexgrand.com'
  - url: 'https://secure.fxgtrade.com'
  - url: 'https://secure.fxginvest.com'
  - url: 'https://secure.wercrypto.com'
paths:
  /api/affiliatets/autologin:
    get:
      summary: Get link for auto-login
      description:
        Returns link that allows to auto-login into trader personal area.
        Link works only for newly registered leads, i.e. leads without deposit.
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
          description: CRM Lead ID
      responses:
        '200':
          description: Correct response
          content:
            application/json:
              schema:
                properties:
                  loginUrl:
                    type: string
                    description: Link for automatic login (i.e. without login/pass)
                example:
                  loginUrl: https://dev02.bo.avrath.net/Account/TokenLogin?code=3fda080ae93840f68aa4055e3fc7b8ac434da51d64e0458390394766c1855235
        '404':
          description: CRM Lead ID not found
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                example:
                  message: client not found
  /api/affiliatets/clientinfo:
    get:
      summary: Get client info
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
          description: CRM Lead ID
      responses:
        '200':
          description: Correct response
          content:
            application/json:
              schema:
                properties:
                  action:
                    type: string
                    description: type of profile #(always Lead)
                  btag:
                    type: string
                    description: will be provided by Affiliate Tracking Software as query string on the landing pages and site pages
                  rdate:
                    type: string
                    description: date of registration
                  traderID:
                    type: string
                    description: ID of trading account in trading platform
                  status:
                    type: string
                    description: if the registration considered as an active (real account) or demo
                  country: 
                    type: string
                    description: Lead's country (ISO code 2 characters)
                  leadStatus:
                    type: string
                    description: Lead status
                  leadSource:
                    type: string
                    description: method Lead was created with (integration/manual/import/backoffice)
                  lastLoginDate:
                    type: string
                    description: date of Lead's last login
                  promoCode:
                    type: string
                    description: promo-code
                  crmLeadId:
                    type: string
                    description: ID of Lead in CRM system
                  mtmGroupName: 
                    type: string
                    description: Partner's goup name in MetaTrader4
                  leadSourceType:
                    type: string
                    description: name of Lead Source
                  partnerName:
                    type: string
                    description: Partner's name in CRM system
                example:
                  action: lead
                  btag: 14b5cf95-52cb
                  rdate: 2017.01.01 01:01:01
                  traderID: 1111111111
                  status: lead
                  country: RU
                  leadStatus: hot
                  leadSource: integration
                  lastLoginDate: 2017.01.01 01:11:01
                  promoCode: 111
                  crmLeadId: 11111
                  mtmGroupName: xxx-xxx-xxx
                  leadSourceType: LeadSource1
                  partnerName: Partner1
        '404':
          description: CRM Lead ID not found
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                example:
                  message: client not found
  /api/affiliatets/transactions:
    get:
      summary: Deposits and withdrawals.
      description: Returns information on deposits and withdrawals transactions.
      parameters:
        - $ref: '#/components/parameters/fromParam'
        - $ref: '#/components/parameters/toParam'
        - $ref: '#/components/parameters/rowsParam'
        - $ref: '#/components/parameters/pageParam'
      responses:
        '200':
          description: Correct response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/trans'
  /api/affiliatets/stats:
    get:
      summary: Trading transactions.
      description: Returns information on trading transactions.
      parameters:
        - $ref: '#/components/parameters/fromParam'
        - $ref: '#/components/parameters/toParam'
        - $ref: '#/components/parameters/rowsParam'
        - $ref: '#/components/parameters/pageParam'
      responses:
        '200':
          description: Correct response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/stats'
  /api/affiliatets/registration:
    get:
      summary: Leads registration.
      description: Returns information on Leads' registration.
      parameters:
        - $ref: '#/components/parameters/fromParam'
        - $ref: '#/components/parameters/toParam'
        - $ref: '#/components/parameters/rowsParam'
        - $ref: '#/components/parameters/pageParam'
      responses:
        '200':
          description: Correct response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/regs'
components:
  parameters:
    fromParam:
      in: query
      name: from
      description: start of a period
      required: true
      schema:
        type: string
        format: dateTime
      example: "2017-01-01"
    toParam:
      in: query
      name: to
      description: end of a period
      required: true
      schema:
        type: string
        format: dateTime
      example: "2017-01-01"
    rowsParam:
      in: query
      name: rows
      description: number of rows in a page
      required: true
      schema:
        type: integer
      example: 100
    pageParam:
      in: query
      name: page
      description: page number
      required: true
      schema:
        type: integer
      example: 1
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
  schemas:
    regs:
      type: object
      properties:
        action:
          type: string
          description: type of profile #(always Lead)
        status:
          type: string
          description: if the registration considered as an active (real account) or demo
        rdate:
          type: string
          description: date of registration
        traderID:
          type: string
          description: ID of trading account in trading platform
        lastLoginDate:
          type: string
          description: date of Lead's last login
        leadStatus:
          type: string
          description: Lead status
        country: 
          type: string
          description: Lead's country (ISO code 2 characters)
        promoCode:
          type: string
          description: Lead's promo
        crmLeadId:
          type: string
          description: ID of Lead in CRM system
        leadSource:
          type: string
          description: method Lead was created with (integration/manual/import/backoffice)
        leadSourceType:
          type: string
          description: name of Lead Source
        mtmGroupName: 
          type: string
          description: Partner's goup name in MetaTrader4
        partnerName:
          type: string
          description: Partner's name in CRM system
        email:
          type: string
          description: Lead's email
      example:
        action: lead
        status: lead
        rdate: "2017-01-01 01:01:01"
        traderID: "1111111111"
        lastLoginDate: "2017-01-01 01:11:01"
        leadStatus: hot
        country: RU
        promoCode: "111"
        crmLeadId: "11111"
        leadSource: integration
        leadSourceType: LeadSource1
        mtmGroupName: xxx-xxx-xxx
        partnerName: Partner1
        email: example@example.com
    stats:
      type: object
      properties:
        rdate:
          type: string
          description: date of transaction
        traderID:
          type: string
          description: ID of trading account in trading platform
        tranzID:
          type: string
          description: ID of transaction in trading platform
        type:
          type: string
          description: type of transaction (deposit/withdrawal)
        amount:
          type: string
          description: amount of transaction
        currency:
          type: string
          description: currency of transaction
        status:
          type: string
          description: status of transaction
        usdAmount: 
          type: string
          description: amount of transaction in USD currency
        crmLeadId:
          type: string
          description: ID of a Lead in CRM system
      example:
        rdate: "2017-01-01 01:01:01"
        traderID: "11111111111"
        tranzID: "1"
        type: pnl
        amount: "1000"
        currency: usd
        status: approval
        usdAmount: "1000"
        crmLeadId: "111111"
    trans: 
      type: object
      properties:
        rdate:
          type: string
          description: date of transaction
        traderID:
          type: string
          description: ID of trading account in trading platform
        tranzID:
          type: string
          description: ID of transaction in trading platform
        type:
          type: string
          description: type of transaction (deposit/withdrawal)
        amount:
          type: string
          description: amount of transaction
        currency:
          type: string
          description: currency of transaction
        status:
          type: string
          description: status of transaction
        crmLeadId:
          type: string
          description: ID of a Lead in CRM system
      example:
        rdate: "2017-01-01 01:01:01"
        traderID: "1111111111"
        tranzID: "1"
        type: deposit
        amount: "1000"
        currency: usd
        status: approval
        crmLeadId: "111111"
security:
  - ApiKeyAuth: []
