openapi: 3.0.0
info:
  title: Leads
  version: 1.0.0
servers:
  - url: 'https://crm.uteclab.com'
paths:
  /api/lead:
    get:
      summary: Receive parameters.
      description: >
        Returns the list of parameters and it's properties, required to create
        Lead.

        Request sends to CRM system URL followed by /api/lead.
      responses:
        '200':
          description: Correct response
          content:
            application/x-www-form-urlencoded:
              schema:
                $ref: '#/components/schemas/AllowedParameters'
            application/json:
              schema:
                $ref: '#/components/schemas/AllowedParameters'
  /api/v2/lead:
    post:
      summary: Create Lead in CRM.
      description: > 
        Allows to create Leads with a POST-request to CRM system URL followed by /api/v2/lead.
      operationId: addLead
      requestBody:
        description: Lead info
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/NewLead'
          application/json:
            schema:
              $ref: '#/components/schemas/NewLead'
      responses:
        '200':
          description: Correct response
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    description: |
                      "OK" 
                      - Lead was created.

                      "Missing fields: " + list of missing fields 
                      - Some of parameters are missing.
                      
                      "Request body must contain UFT-8 characters only" 
                      - Incorrect request format.
                      
                      "Error type: " + 
                        "The string supplied was too long to parse" or
                        "The phone number supplied was null" or
                        "The string supplied did not seem to be a phone number" or
                        "Could not interpret numbers after plus-sign" or
                        "The string supplied is too short to be a phone number" or
                        "The string supplied is too long to be a phone number" or
                        "Phone number had an IDD, but after this was not long enough 
                         to be a viable phone number" or
                        "Country calling code supplied was not recognized" 
                        - Phone validation failed (only when autofix_phone = true)
                      
                      "Phone Number cannot be blank" or
                      "Email cannot be blank" or
                      "Language cannot be blank" or
                      "Country cannot be blank" or
                      "First name cannot be blank"
                      - Required parameter is null.
                      
                      "Broker not set" 
                      - CRM system is not initialized.
                      
                      "Integration disabled" 
                      - Integration is disabled for the Lead Source.
                      
                      "Incorrect source"
                      - Lead Source is deleted.
                      
                      "Token is invalid"
                      - Invalid token.
                    enum:
                    - OK.
                    - Missing fields + list of missing fields
                    - Request body must contain UFT-8 characters only
                    - The string supplied was too long to parse
                    - The phone number supplied was null
                    - The string supplied did not seem to be a phone number
                    - Could not interpret numbers after plus-sign
                    - The string supplied is too short to be a phone number
                    - The string supplied is too long to be a phone number
                    - Phone number had an IDD, but after this was not long enough 
                      to be a viable phone number
                    - Country calling code supplied was not recognized
                    - Email cannot be blank
                    - Phone Number cannot be blank
                    - Language cannot be blank
                    - Country cannot be blank
                    - First name cannot be blank
                    - Broker not set
                    - Integration disabled
                    - Incorrect source
                    - Token is invalid
                  leadId:
                    type: string
                  autoLoginLink:
                    type: string
                example:
                  message:
                    Message: OK
                  leadId: 37769
                  autoLoginLink: https://dev02.bo.avrath.net/Account/TokenLogin?code=3fda080ae93840f68aa4055e3fc7a8ac434da51d64e0458390394766c1855235
  /api/check-email:
    post:
      summary: Check the availability of email.
      description: >
        Sends POST-request to CRM system URL followed by /api/check-email.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckEmailRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CheckEmailRequest'
      responses:
        '200':
          description: Correct response
          content:
            "*/*": {}
  /api/check-phone:
    post:
      summary: Check the availability of phone number.
      description: >
        Sends POST-request to CRM system URL followed by /api/check-phone.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckPhoneRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CheckPhoneRequest'
      responses:
        '200':
          description: Correct response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckResponse'
components:
  schemas:
    CheckEmailRequest:
      properties:
        email:
          type: string
    CheckPhoneRequest:
      properties:
        phone_number:
          type: string
    AllowedParameters:
      properties:
        phone_number:
          type: array
          items:
            type: string
        language:
          type: string
        first_name:
          type: array
          items:
            type: string
        country:
          type: string
        promo_code:
          type: string
        last_name:
          type: string
        address:
          type: string
        email:
          type: string
        token:
          type: string
    CheckResponse:
      properties:
        exist:
          type: boolean
    NewLead:
      required:
        - phone_number
        - language
        - first_name
        - last_name
        - country
        - address
        - email
      properties:
        phone_number:
          type: string
        language:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        country:
          type: string
        address:
          type: string
        email:
          type: string
        promo-code:
          type: string
        token:
          type: string
        referer:
          type: string
        comment:
          type: string
        autofix_phone:
          type: boolean
      example:
        phone_number: +11111111111
        language: English
        first_name: John
        last_name: Smith
        country: United States
        address: Main st.1
        email: johnsmith@example.com
