---
openapi: 3.0.0
info:
  title: Leads
  description: Sample Leads description
  version: 1.0.0
servers:
  - url: http://crm.uteclab.com
paths:
  /api/lead:
    get:
      responses:
        '200':
          content:
            application/json: {}
