openapi: 3.0.0
info:
  title: Leads
  version: 1.0.0
servers:
  - url: 'https://crm.uteclab.com'
paths:
  /api/lead:
    get:
      summary: receive parameters
      description: >
        Returns the list of parameters and it's properties, required to create
        Lead.

        Request sends to CRM system URL followed by /api/lead.
      responses:
        '200':
          description: correct response
          content:
            application/json: {}
  /api/v2/lead:
    post:
      description: Creates a Lead in CRM.
      operationId: addLead
      requestBody:
        description: Lead to create
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/NewLead'
      responses:
        '200':
          description: Lead created
          content:
            application/json: {}
components:
  schemas:
    NewLead:
      required:
        - phone_number
        - language
        - first_name
        - last_name
        - country
        - address
        - email
      properties:
        phone_number:
          type: string
          format: base64
        language:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        country:
          type: string
        address:
          type: string
        email:
          type: string
        promo-code:
          type: string
        token:
          type: string
        referer:
          type: string
        comment:
          type: string
        autofix_phone:
          type: boolean
      example:
        phone_number: +11111111111
        language: English
        first_name: John
        last_name: Smith
        country: United States
        address: Main st.1
        email: johnsmith@example.com
        
