openapi: 3.0.0
info:
  title: Leads
  version: 1.0.0
servers:
  - url: 'https://crm.uteclab.com'
paths:
  /api/lead:
    get:
      summary: Receive parameters.
      description: >
        Returns the list of parameters and it's properties, required to create
        Lead.

        Request sends to CRM system URL followed by /api/lead.
      responses:
        '200':
          description: Correcr request
          content:
            application/x-www-form-urlencoded:
              schema:
                $ref: '#/components/schemas/AllowedParameters'
            application/json:
              schema:
                $ref: '#/components/schemas/AllowedParameters'
  /api/v2/lead:
    post:
      summary: Create Lead in CRM.
      description: > 
        Allows to create Leads with a POST-request to CRM system URL followed by /api/v2/lead.
      operationId: addLead
      requestBody:
        description: Lead info
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/NewLead'
          application/json:
            schema:
              $ref: '#/components/schemas/NewLead'
      responses:
        '200':
          description: Correcr request
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                  leadId:
                    type: string
                  autoLoginLink:
                    type: string
                example:
                  message:
                    Message: OK
                  leadId: null   ######################
                  autoLoginLink: null #################
  /api/check-email:
    post:
      summary: Check the availability of email.
      description: >
        Sends POST-request to CRM system URL followed by /api/check-email.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckEmailRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CheckEmailRequest'
      responses:
        '200':
          description: Correcr request
          content:
            "*/*": {}
  /api/check-phone:
    post:
      summary: Check the availability of phone number.
      description: >
        Sends POST-request to CRM system URL followed by /api/check-phone.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckPhoneRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CheckPhoneRequest'
      responses:
        '200':
          description: Correcr request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckResponse'
components:
  schemas:
    CheckEmailRequest:
      properties:
        email:
          type: string
    CheckPhoneRequest:
      properties:
        phone_number:
          type: string
    AllowedParameters:
      properties:
        phone_number:
          type: array
          items:
            type: string
        language:
          type: string
        first_name:
          type: array
          items:
            type: string
        country:
          type: string
        promo_code:
          type: string
        last_name:
          type: string
        address:
          type: string
        email:
          type: string
        token:
          type: string
    CheckResponse:
      properties:
        exist:
          type: boolean
    NewLead:
      required:
        - phone_number
        - language
        - first_name
        - last_name
        - country
        - address
        - email
      properties:
        phone_number:
          type: string
        language:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        country:
          type: string
        address:
          type: string
        email:
          type: string
        promo-code:
          type: string
        token:
          type: string
        referer:
          type: string
        comment:
          type: string
        autofix_phone:
          type: boolean
      example:
        phone_number: +11111111111
        language: English
        first_name: John
        last_name: Smith
        country: United States
        address: Main st.1
        email: johnsmith@example.com
