---
openapi: 3.0.0
info:
  title: Leads
  version: 1.0.0
servers:
- url: http://crm.uteclab.com
paths:
  /api/lead:
    description: wqeqe
    get:
      responses:
        '200':
          description: wqeqe
          content:
            application/json: {}
