openapi: 3.0.0
info:
  title: Leads
  version: 1.0.0
servers:
  - url: 'https://crm.uteclab.com'
paths:
  /api/lead:
    get:
      summary: receive parameters
      description: >
        Returns the list of parameters and it's properties, required to create
        Lead.

        Request sends to CRM system URL followed by /api/lead.
      responses:
        '200':
          content:
            application/json: {}
  /api/v2/lead:
    post:
      description: Creates a new pet in the store.  Duplicates are allowed
      operationId: addPet
      requestBody:
        description: Pet to add to the store
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/NewLead'
      responses:
        '200':
          content:
            application/json: {}
components:
  schemas:
    NewLead:
      required:
        - phone_number  
      properties:
        phone_number:
          type: string
          
        
