---
openapi: 3.0.0
info:
  title: Leads
  version: 1.0.0
servers:
  - url: https://crm.uteclab.com
paths:
  /api/lead:
    get:
    summary: receive parameters
      responses:
        '200':
          content:
            application/json: {}
