---
openapi: 3.0.0
info:
  title: Leads
  version: 1.0.0
servers:
  - url: https://crm.uteclab.com
paths:
  /api/lead:
    get:
      summary: receive parameters
      description: |
        Returns the list of parameters and it's properties, required to create Lead.
        Request sends to CRM system URL followed by /api/lead.
      responses:
        '200':
          content:
            application/json: {}
    post:
      summary: create Lead
      description: |
        Creates Lead in CRM system.
      parameters:
        - name: phone_number
          in: body
          type: string
          description: Lead's phone number.
          required: true
          default: '123124543545623234'
        - name: language
          in: body
          type: string
          description: Lead's language.
          required: true
          default: 'English'
        - name: first_name
          in: body
          type: string
          description: Lead's first name.
          required: true
          default: 'Gabriel'
        - name: last_name
          in: body
          type: string
          description: Lead's surname.
          required: true
          default: 'Smith'
        - name: country
          in: body
          type: string
          description: Lead's country.
          required: true
          default: 'Russia'
        - name: address
          in: body
          description: Lead's address.
          required: true
          default: 'far-far away'
        - name: email
          in: body
          type: string
          description: Lead's email.
          required: true
          default: 'egzampil11@example.com'
        - name: promo_code
          in: body
          type: string
          description: Promo-code.
          required: false
        - name: token
          in: body
          type: string
          description: Lead Source's token.
          required: false
          default: 'rxhOGnShCv1aHlerl4NYANX3dJ-QuwTt'
        - name: referer
          in: body
          type: string
          description: Lead Source's name in readable format.
          required: false
        - name: comment
          in: body
          type: string
          description: Comment to a lead's profile.
          required: false
        - name: autofix_phone
          in: body
          type: bool
          description: Use/Not use advanced validation of phone number.
          required: false
      responses:
        "200":
          description: Lead response
          schema:
            $ref: '#/definitions/Lead'
        "400":
          description: Bad req
          schema:
            $ref: '#/definitions/Error'
        default:
          description: error
          schema:
            $ref: '#/definitions/Error'
  /api/v2/lead:
    post:
      summary: create Lead
      description: |
        Creates Lead in CRM system. 
      parameters:
        - name: phone_number
          in: query
          type: string
          description: Lead's phone number.
          required: true
        - name: language
          in: query
          type: string
          description: Lead's language.
          required: true 
        - name: first_name
          in: query
          type: string
          description: Lead's first name.
          required: true
        - name: last_name
          in: query
          type: string
          description: Lead's surname.
          required: true
        - name: country
          in: query
          type: string
          description: Lead's first name.
          required: true
        - name: address
          in: query
          description: Lead's address.
          required: true
        - name: email
          in: query
          type: string
          description: Lead's email.
          required: true
        - name: promo_code
          in: query
          type: string
          description: Promo-code.
          required: false
        - name: token
          in: query
          type: string
          description: Lead Source's token.
          required: false
        - name: referer
          in: query
          type: string
          description: Lead Source's name in readable format.
          required: false
        - name: comment
          in: query
          type: string
          description: Comment to a lead's profile.
          required: false
        - name: autofix_phone
          in: query
          type: bool
          description: Use/Not use advanced validation of phone number.
          required: false
definitions:
  Lead:
    allOf:
      - $ref: '#/definitions/NewLead'
      - required:
        - id
        properties:
          id:
            type: integer
            format: int64

  NewLead:
    required:
      - name  
    properties:
      name:
        type: string
      tag:
        type: string    

  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
